- name: Enable Webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Install latest httpd
      yum:
        name: httpd
        state: latest

    - name: Install latest firewalld
      yum:
        name: firewalld
        state: latest

    - name: Permit http traffic
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Permit ssh traffic
      firewalld:
        service: ssh
        permanent: true
        state: enabled
        immediate: yes

    - name: Enable httpd
      service: 
        name: httpd
        enabled: true
        state: started

    - name: Enable firewalld
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Check SELinux
      selinux:
        policy: targeted
        state: enforcing

    - name: Deploy the web page
      copy:
        src: /home/tquinlan/Documents/blogs/Ansible/example_files/index.html
        dest: /var/www/html
        owner: apache
        group: apache
        mode: 0644
